version: 0.2
env:
  secrets-manager:
    APPLITOOLS_API_KEY: "APPLITOOLS_API_KEY"

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm test
artifacts:
  files:
    - '**/*'